development:
  adapter: postgresql
  encoding: utf8
  database: transport-tracker-development
  pool: 5
  username: postgres
  password: password
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: transport-tracker-test
  pool: 5
  username: postgres
  password: password
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: transport-tracker-production
  pool: 5
  username: postgres
  password: password
  host: localhost
