development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: dmce103@gmail.com
  :password: dm103_tsk
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: dmce103@gmail.com
  :password: dm103_tsk
  :enable_starttls_auto: true